owsolutions/angular5-iot-dashboard

.travis.yml

Only deploy to firebase when it's master branch.

Add condition

---

src/_medias.scss
src/_mixins.scss
src/_vars.scss

Adds some mixins and variables to the project. Won't make any effect on the project behavior.

Importing mixins

---

src/app/settings/settings.component.html
src/app/summary/summary.component.html
src/styles.scss

Adds a default page header style for router-outlet pages h1.page-title

Adding default page header

---

src/app/devices/devices.component.html
src/app/devices/devices.component.scss
src/app/shared/device-svg/device-svg.component.html
src/index.html
src/styles.scss

Fixed pin configuration style in responsive mode 
for opening like angular bottom sheet create public function to manage this animation please review that function and check functionalities

Pin configuration open from bottom to up

---

package.json

Make production for ng build

---

src/app/activity/activity.component.html
src/app/app.module.ts
src/app/devices/devices.component.html
src/app/locations/locations.component.html
src/app/settings/settings.component.html
src/app/shared/page-header/page-header.component.html
src/app/shared/page-header/page-header.component.scss
src/app/shared/page-header/page-header.component.spec.ts
src/app/shared/page-header/page-header.component.ts
src/app/summary/summary.component.html
src/styles.scss

Replace all components page header with a new component, called: "page-header". Keeps it consistent to use same header across all pages.

Replace all headers with page-header component

---

src/app/communicate.service.ts
src/app/index/chart/chart.component.html

Adding widgets mock based on generated devices and locations. in rx code there is a callback hell because I am not sure to select multiple values from rxjs ( combine ) them.
Works pretty well regardless of code mistakes.

Mocking widgets based on devices and locations

---

.travis.yml

Attempts to run chrome based testing on travis for angular project.

Update code to be able to run in travis

---

package.json

Increase the version

---

src/app/index/places/places.component.html
src/app/index/places/places.component.ts
src/app/locations/location-row/location-row.component.html
src/app/locations/location-row/location-row.component.spec.ts
src/app/locations/location-row/location-row.component.ts
src/app/locations/locations.component.html
src/app/locations/locations.component.ts
src/app/shared/output-pin/output-pin.component.html
src/app/shared/output-pin/output-pin.component.ts

Currently location row has fake data, temperature and etc. Make sure they are binded to location widgets instead of hard coded values.
By adding this PR, it will be connected to widgets of the location and output pins will be connected, temperature feature will still remain as hardcoded.

Connect the places to widgets

---

src/app/devices/devices.component.html
src/app/devices/devices.component.scss
src/app/widgets/widgets.component.html
src/app/widgets/widgets.component.scss

Bunch of UI improvements for better user experience.

Devices and widgets padding update

---

src/app/routes.ts
src/app/shared/navigation/navigation.component.ts

Adds the form elements page on the navigation.

Dispaly forms in navigation

---

src/app/layout/quick-status/quick-chart/quick-chart.component.scss

Fixes quick status sidebar issue on firefox.

Update the position relative on firefox

---

src/app/forms/checkbox-input/checkbox-input.component.html
src/app/forms/checkbox-input/checkbox-input.component.ts
src/app/permissions.service.ts
src/app/roles/roles.component.html
src/app/shared/Definitions.ts
src/assets/css/forms-style.css

Checkboxes

---

src/app/iot/shared/output-pin/output-pin.component.scss
src/app/iot/shared/switch-widgets/switch-widgets.component.scss

Fix widgets

---

src/app/core/services/user.service.ts

Update user service to redirect to login

---

src/app/app.routes.ts
src/app/authentication/login-form/login-form.component.ts
src/app/services/user.service.ts

Update the code

---

src/app/app.module.ts
src/app/app.navigation.ts
src/app/app.routes.ts
src/app/components/docs/docs.component.html
src/app/components/docs/docs.component.ts
src/app/components/docs/sending-information-https/sending-information-https.component.html
src/app/components/docs/sending-information-https/sending-information-https.component.spec.ts
src/app/components/docs/sending-information-https/sending-information-https.component.ts
src/environments/environment.hmr.ts

Separates the documents component into multi-level components, for each endpoint, we will write this one.

41 separate the documents into smaller components

---

src/app/components/index/index.component.html
src/app/components/statistics/statistics.component.html

Add the new index statistics design.

Update index statistics

---

src/app/app.module.ts
src/app/app.routes.ts
src/app/authentication/signup-form/signup-form.component.html
src/app/components/privacy-policy/privacy-policy.component.html
src/app/components/privacy-policy/privacy-policy.component.scss
src/app/components/privacy-policy/privacy-policy.component.spec.ts
src/app/components/privacy-policy/privacy-policy.component.ts

Adds a simple privacy policy page for the application.

Add privacy policy component

---

src/app/authentication/authentication.module.ts
src/app/authentication/error-message/error-message.component.html
src/app/authentication/error-message/error-message.component.scss
src/app/authentication/error-message/error-message.component.spec.ts
src/app/authentication/error-message/error-message.component.ts
src/app/authentication/signup-form/signup-form.component.html
src/app/authentication/signup-form/signup-form.component.scss
src/app/services/mocks.service.ts
src/environments/environment.hmr.ts

Fixes some minor UI issues inside the signup form to give users a better feeling when they are signing-up to the dashboard.

Update the signup form for a better user experience

---

src/app/components/device-general-information/device-general-information.component.html

When user has no location, we hide the select box for locations.

Hide the locations in device single

---

src/app/authentication/common.scss
src/app/authentication/login-form/login-form.component.html
src/app/services/mocks.service.ts

Update the signin form to give a better user experience.

Update the login form

---

src/app/services/token.interceptor.ts

When user has no access to the endpoint, we will return him to login page.

If any endpoint returns 401, return to login page

---

src/app/components/device-single/device-single.component.html
src/app/components/layout/layout.component.html
src/app/components/layout/layout.component.ts
src/app/components/nav-bar/nav-bar.component.scss
src/app/components/progress-line/progress-line.component.scss
src/app/components/side-bar/side-bar.component.scss

Update minor UI issues for displaying progressbar while app is loading.

Add the progress bar for layout and device single

---

src/app/data-layer/activity.reducer.ts
src/app/data-layer/devices.reducer.ts
src/app/data-layer/locations.reducer.ts
src/app/data-layer/notifications.reducer.ts
src/app/data-layer/roles.reducer.ts
src/app/data-layer/unconnectedSources.reducer.ts
src/app/services/user.service.ts

Clear the store data when user signout.

Reset the store

---

src/app/app.module.ts
src/app/app.navigation.ts
src/app/app.routes.ts
src/app/components/contact-details/contact-details.component.html
src/app/components/contact-details/contact-details.component.spec.ts
src/app/components/contact-details/contact-details.component.ts
src/app/components/locations/locations.component.html
src/app/definitions.ts
src/app/services/mocks.service.ts
src/app/services/notification.service.ts
src/app/services/requests.service.ts

Creates a new menu in navigation in none production mode, to collect the user contact options, such as email, phone, and etc.

86 collect user contact information

---

package.json
src/app/components/docs/docs.component.ts
src/app/components/docs/sending-information-https/sending-information-https.component.html
src/app/components/docs/sending-information-https/sending-information-https.component.ts

Add the document API to show the YAML file as well.

95 add the yml information on documents

---

src/app/app.navigation.ts

Removes the experimental flag for contact information. Now in production you can collect user production information.

Remove the experimental flag

---

cypress/integration/roles_spec.js
src/app/app.module.ts
src/app/app.navigation.ts
src/app/app.routes.ts
src/app/components/device-single/device-single.component.html
src/app/components/page-container/page-container.component.html
src/app/components/role-single/role-single.component.html
src/app/components/role-single/role-single.component.scss
src/app/components/role-single/role-single.component.ts
src/app/components/roles/roles.component.html
src/app/components/roles/roles.component.ts
src/app/data-layer/roles.reducer.ts
src/app/ng5-basic/authentication/forgot-password/forgot-password.component.ts
src/app/ng5-basic/layout/layout.component.ts
src/app/services/actions.service.ts
src/app/services/mocks.service.ts
src/app/services/notification.service.ts
src/app/services/requests.service.ts

Adds an experimental roles management. In every app, we are having different level of access, so we define roles and managing them.
**Experimental flags might be removed when they are working on the api side.**

129 add role management list

---

src/app/app.navigation.ts
src/app/components/role-single/role-single.component.html

Puts the role module into production.

Move the role to production

---

src/app/common.ts
src/app/iot/docs/docs.component.ts
src/app/iot/docs/sending-information-https/sending-information-https.component.ts
src/app/iot/iot-mocks.service.ts
src/app/iot/iot-requests.service.ts
src/app/iot/realtime.service.ts
src/app/ng5-basic/authentication/login-form/login-form.component.ts
src/app/ng5-basic/authentication/reset-password/reset-password.component.ts
src/app/ng5-basic/authentication/signup-form/signup-form.component.ts
src/app/services/mocks.service.ts
src/app/services/requests.service.ts
src/app/users/user-mocks.service.ts
src/app/users/user-requests.service.ts
src/environments/environment.github.ts
src/environments/environment.hmr.ts
src/environments/environment.prod.ts
src/environments/environment.prodlocal.ts
src/environments/environment.prodmock.ts
src/environments/environment.ts

We had some hard coded prefix for the api. that's not nice.

Change all prefixes and use one function

---

src/app/components/settings/settings.component.html
src/app/components/settings/settings.component.ts
src/app/iot/index/index.component.ts
src/app/iot/iot-requests.service.ts
src/app/iot/iot.module.ts
src/app/iot/realtime.service.ts
src/environments/environment.hmr.ts

Adds short token on the project settings. Helps to get shorter codes.

Adding the short token
